# Generated by Django 3.2.6 on 2022-06-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_is_service_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('group_added', 'User added to new group'), ('group_deleted', 'User removed from group'), ('permission_added', 'New permission added to group'), ('permission_deleted', 'Permission removed from group'), ('env_created', 'Environment created'), ('env_deleted', 'Environment deleted'), ('services_changed', 'Services changed')], max_length=30, null=True)),
                ('context', models.JSONField(default=dict)),
                ('environments', models.JSONField(default=list)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
    ]
