# Generated by Django 3.2.6 on 2022-10-10 12:25

import billing.models.tally
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_slug'),
        ('projects', '0067_auto_20220928_1611'),
        ('billing', '0002_auto_20220610_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('period', models.DurationField(default=billing.models.tally.default_tally_period)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallies', to='users.account')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallies', to='projects.environment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallies', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TallyMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('tally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='billing.tally')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tallymark',
            constraint=models.UniqueConstraint(fields=('tally', 'time'), name='unique_tally_and_time'),
        ),
        migrations.AddConstraint(
            model_name='tally',
            constraint=models.UniqueConstraint(fields=('account', 'project', 'environment', 'name'), name='unique_scope_and_name'),
        ),
    ]
