# Generated by Django 3.2.6 on 2022-10-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20221013_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='kind',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth')], default='starter', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
