# Generated by Django 3.2.6 on 2022-10-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20221019_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Zero means no trial period.'),
        ),
    ]
