# Generated by Django 3.2.6 on 2022-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_trial_period_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stripe_data', models.JSONField(default=dict)),
                ('tally_name', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='prices',
        ),
        migrations.AddField(
            model_name='plan',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
