# Generated by Django 3.2.6 on 2022-11-15 21:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20221028_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='error_details',
            field=models.TextField(blank=True, help_text='Details about processing error if existed', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed successfully'), ('ignored', 'Processing not required'), ('failed', 'Failed processing')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Users with access to at least one code-server pod'),
        ),
        migrations.AddField(
            model_name='product',
            name='charges_per_seat',
            field=models.BooleanField(default=False, help_text='If charges per user with access to at least one code-server pod'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_name',
            field=models.CharField(blank=True, help_text='Used to associate services that need to be charged by instance', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('groups_added', 'User added to new groups'), ('groups_deleted', 'User removed from groups'), ('permissions_added', 'New permissions added to group'), ('permissions_deleted', 'Permissions removed from group'), ('env_created', 'Environment created'), ('env_deleted', 'Environment deleted'), ('services_changed', 'Services changed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tally_name',
            field=models.SlugField(blank=True, help_text='The name of a tally that keeps track of the usage for this product', null=True),
        ),
    ]
