# Generated by Django 3.2.6 on 2022-11-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20221115_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallymark',
            name='error_details',
            field=models.TextField(blank=True, help_text='Details about processing error if existed', null=True),
        ),
        migrations.AddField(
            model_name='tallymark',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tallymark',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed successfully'), ('failed', 'Failed processing')], default='pending', max_length=30),
        ),
    ]
