# Generated by Django 3.2.6 on 2022-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20221116_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Processed successfully'), ('I', 'Processing not required'), ('F', 'Failed processing')], default='P', max_length=30),
        ),
        migrations.AlterField(
            model_name='tallymark',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Processed successfully'), ('I', 'Processing not required'), ('F', 'Failed processing')], default='P', max_length=30),
        ),
    ]
