# Generated by Django 3.2.6 on 2022-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20221117_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='kind',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('custom', 'Custom')], default='starter', max_length=20),
        ),
    ]
