# Generated by Django 3.2.6 on 2022-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_plan_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
