# Generated by Django 3.2.6 on 2022-11-15 18:49

import billing.models.plan
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_plan_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='workers_execution_limit',
            field=models.JSONField(default=billing.models.plan.get_default_workers_execution_limit, null=True),
        ),
    ]
