# Generated by Django 3.2.16 on 2023-03-03 14:12

import billing.models.plan
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20221206_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='developer_licenses',
            field=models.PositiveIntegerField(default=0, help_text='Max number of developer licenses (users with access to at least one code-server pod), zero means infinite.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='workers_execution_limit',
            field=models.JSONField(default=billing.models.plan.get_default_workers_execution_limit, help_text='max execution seconds allowed per period at plan level', null=True),
        ),
    ]
