# Generated by Django 3.2.20 on 2023-11-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20230303_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='items',
            new_name='variants',
        ),
    ]
