# Generated by Django 5.0.7 on 2024-11-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_auto_20240701_2118"),
        ("users", "0022_user_setup_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="Date when credit starts being applicable"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        help_text="Date when credit stops being applicable"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Descriptive credit reference", max_length=250
                    ),
                ),
                (
                    "developer_seats",
                    models.PositiveIntegerField(
                        default=0, help_text="Developer seats credit"
                    ),
                ),
                (
                    "airflow_instances",
                    models.PositiveIntegerField(
                        default=0, help_text="Airflow instances credit"
                    ),
                ),
                (
                    "airbyte_instances",
                    models.PositiveIntegerField(
                        default=0, help_text="Airbyte instances credit"
                    ),
                ),
                (
                    "superset_instances",
                    models.PositiveIntegerField(
                        default=0, help_text="Superset instances credit"
                    ),
                ),
                (
                    "datahub_instances",
                    models.PositiveIntegerField(
                        default=0, help_text="Datahub instances credit"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.account"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
