{
 "title": "Airflow Service",
 "description": "Airflow Service",
 "tags": [ "Airflow" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "Env" }
  ]
 },
 "panels": [
  { "title": "Airflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Slots Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (airflow_executor_open_slots{namespace=\"dcw-$env\"} + airflow_executor_running_tasks{namespace=\"dcw-$env\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (namespace) (airflow_executor_open_slots{namespace=\"dcw-$env\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Busy Task Slots",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (airflow_executor_running_tasks{namespace=\"dcw-$env\"} / (airflow_executor_open_slots{namespace=\"dcw-$env\"} + airflow_executor_running_tasks{namespace=\"dcw-$env\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Bag Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_dagbag_size{namespace=\"dcw-$env\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAGs  Import Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (airflow_dag_processing_import_errors{namespace=\"dcw-$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dag Run",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT dag_id, run_id, state, execution_date, start_date, end_date, end_date - start_date as duration\nFROM dag_run\nWHERE start_date BETWEEN $__timeFrom() AND $__timeTo()\nOR end_date BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY start_date DESC\nLIMIT 200"
    }
   ]
  },
  {
   "title": "Tasks Slots Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (namespace) (airflow_executor_open_slots{namespace=\"dcw-$env\"})",
     "legendFormat": "open slots"
    },
    {
     "expr": "sum by (namespace) (airflow_executor_running_tasks{namespace=\"dcw-$env\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by (namespace) (airflow_executor_queued_tasks{namespace=\"dcw-$env\"})",
     "legendFormat": "queued"
    },
    {
     "expr": "sum by (namespace) (rate(airflow_scheduler_tasks_killed_externally{namespace=\"dcw-$env\"}[$__rate_interval]))",
     "legendFormat": "killed"
    }
   ]
  },
  {
   "title": "Scheduler Hearbeat per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat{namespace=\"dcw-$env\"}[1m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tasks Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(round(increase(airflow_ti_successes{namespace=\"dcw-$env\"}[$__rate_interval]))) by (namespace)",
     "legendFormat": "successes"
    },
    {
     "expr": "sum(round(increase(airflow_ti_start{namespace=\"dcw-$env\"}[$__rate_interval]))) by (namespace)",
     "legendFormat": "started"
    },
    {
     "expr": "sum(round(increase(airflow_ti_finish{namespace=\"dcw-$env\"}[$__rate_interval]))) by (namespace)",
     "legendFormat": "finished"
    }
   ]
  },
  {
   "title": "DAGs Sync Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airflow_dag_processing_last_duration_sync_airflow_db{namespace=\"dcw-$env\", quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Tasks",
   "type": "timeseries",
   "description": "Executable: Number of tasks that are ready for execution (set to queued) with respect to pool limits, DAG concurrency, executor state, and priority.\nStarving: Number of tasks that cannot be scheduled because of no open slot in pool.\nRunning: Number of tasks running  on scheduler.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (airflow_scheduler_tasks_executable{namespace=\"dcw-$env\"})",
     "legendFormat": "executable"
    },
    {
     "expr": "sum by (namespace) (airflow_scheduler_tasks_starving{namespace=\"dcw-$env\"})",
     "legendFormat": "starving"
    },
    {
     "expr": "sum by (namespace) (airflow_scheduler_tasks_running{namespace=\"dcw-$env\"})",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Operator Successes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(round(increase(airflow_operator_successes{namespace=\"dcw-$env\", operator!=\"\"}[$__rate_interval]))) by (namespace, operator)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  { "title": "Dag Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "DAGs File processing Time",
   "type": "timeseries",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(airflow_dag_processing_total_parse_time{namespace=\"dcw-$env\"}) by (namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DAGs File Parsing Errors",
   "type": "timeseries",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (airflow_dag_processing_import_errors{namespace=\"dcw-$env\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DAGs Parsing (Top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, label_replace({__name__=~\"airflow_dag_processing_last_duration_.*\", quantile=\"0.99\", namespace=\"dcw-$env\", __name__!~\".*(_sum|_count)$\"}, \"dag_name\", \"$1\", \"__name__\", \"airflow_dag_processing_last_duration_(.+)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Airflow Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Database Pool Active Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgbouncer_exporter_pools_active_clients{database=\"$env-airflow-metadata\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgbouncer_exporter_database_current_connections{name=\"$env-airflow-metadata\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Total Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_exporter_stats_total_query_count{database=\"$env-airflow-metadata\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Scheduler Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "{namespace=\"dcw-$env\", component=\"scheduler\"}"
    }
   ]
  },
  {
   "title": "Scheduler Logs Errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "{namespace=\"dcw-$env\", component=\"scheduler\"} |= `ERROR`"
    }
   ]
  }
 ]
}