{
 "title": "Airflow DAGs Overview",
 "description": "Airflow DAGs Overview",
 "tags": [ "Airflow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "Env" },
   {
    "name": "dag_id",
    "label": "DAG",
    "query": "SELECT dag_id\nFROM dag_run\nWHERE execution_date BETWEEN $__timeFrom() AND $__timeTo()\nLIMIT 200"
   },
   {
    "name": "run_id",
    "label": "Run Id",
    "query": "SELECT run_id\nFROM dag_run\nWHERE dag_id='$dag_id'\nORDER BY id DESC\nLIMIT 5"
   },
   { "name": "pod_name", "label": "Worker" }
  ]
 },
 "panels": [
  {
   "title": "DAG Selected",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h1><strong style=\"color: green\">${dag_id}</strong></h1>\n</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "DAG Runs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT dr.run_id, dr.execution_date, dr.start_date, dr.end_date, dr.run_type, dr.state, sum(ti.duration) \"duration\"\nFROM dag_run dr\nLEFT JOIN task_instance ti ON ti.dag_id=dr.dag_id AND ti.run_id=dr.run_id\nWHERE dr.dag_id = '$dag_id' AND\ndr.start_date BETWEEN $__timeFrom() AND $__timeTo()\nOR dr.end_date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY (dr.id, dr.run_id, dr.execution_date, dr.start_date, dr.end_date, dr.run_type, dr.state)\nORDER BY dr.id DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Task Instance [run_id=$run_id]",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT task_id as task, hostname worker, state, run_id, start_date, end_date, duration as duration\nFROM task_instance\nWHERE dag_id='$dag_id' AND run_id='$run_id'\nORDER BY start_date ASC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Worker Details",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<center>\n<h3>Run ID: <strong style=\"color: green\">$run_id</strong></h3>\n<h3>Worker: <strong style=\"color: green\">$pod_name</strong></h3>\n</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"memory\"})",
     "legendFormat": "memory limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"memory\"})",
     "legendFormat": "memory requets"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"dcw-$env\", container!=\"\", image!=\"\", pod=\"$pod_name\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"memory\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"memory\"}",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"cpu\"})",
     "legendFormat": "cpu limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"cpu\"})",
     "legendFormat": "cpu requets"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"dcw-$env\", pod=\"$pod_name\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"cpu\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"dcw-$env\", pod=\"$pod_name\", resource=\"cpu\"}",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{namespace=\"dcw-$env\", pod=\"$pod_name\"} |= ``"
    }
   ]
  }
 ]
}