apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics-server-v0.6.2.yaml
  - calico-v3.25.yaml
  - cert-manager-v1.11.0.yaml
  - ingress-nginx-v1.6.4.yaml
  # - dashboard-v2.4.0.yaml
  - kind-registry.yaml
  - storage_class_dummies.yaml

patchesStrategicMerge:
  - metrics-server-patch.yaml
  - ingress-nginx-patch.yaml

secretGenerator:
  # TLS certificate for *.datacoveslocal.com
  - name: default-tls
    namespace: ingress-nginx
    type: kubernetes.io/tls
    files:
      - tls.crt=local-cert.cer
      - tls.key=local-cert.key
    options:
      disableNameSuffixHash: true
