# Generated by Django 3.2.6 on 2022-12-29 20:17

import django.db.models.deletion
import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_account_notifications_enabled'),
        ('projects', '0070_blockedpodcreationrequest'),
        ('clusters', '0017_clusteralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('email_sent_to', models.JSONField(blank=True, default=list, null=True)),
                ('statuses', models.JSONField(blank=True, default=notifications.models.get_default_statuses, null=True)),
                ('kind', models.CharField(choices=[('cluster', 'Cluster notification'), ('billing', 'Billing notification')], max_length=10)),
                ('cluster_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.clusteralert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('email_sent_to', models.JSONField(blank=True, default=list, null=True)),
                ('statuses', models.JSONField(blank=True, default=notifications.models.get_default_statuses, null=True)),
                ('kind', models.CharField(choices=[('cluster', 'Cluster notification'), ('billing', 'Billing notification')], max_length=10)),
                ('in_app_read_by', models.JSONField(blank=True, default=list, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('cluster_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.clusteralert')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.environment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
