# Generated by Django 3.2.16 on 2023-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnotification',
            name='link',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
