# Generated by Django 3.2.16 on 2023-02-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20230120_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnotification',
            name='slack_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='slack_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
