# Generated by Django 3.2.20 on 2024-07-01 21:18

from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0039_auto_20240701_2118'),
        ('notifications', '0003_auto_20230208_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnotification',
            name='cluster_alert',
            field=models.ForeignKey(blank=True, help_text='Associated cluster alert, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.clusteralert'),
        ),
        migrations.AlterField(
            model_name='accountnotification',
            name='email_sent_to',
            field=models.JSONField(blank=True, default=list, help_text="JSON list of user ID's the notification was sent to", null=True),
        ),
        migrations.AlterField(
            model_name='accountnotification',
            name='in_app_read_by',
            field=models.JSONField(blank=True, default=list, help_text='Not used?', null=True),
        ),
        migrations.AlterField(
            model_name='accountnotification',
            name='link',
            field=models.JSONField(blank=True, default=dict, help_text='Unused?', null=True),
        ),
        migrations.AlterField(
            model_name='accountnotification',
            name='slack_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Slack metadata is used by slack notification messages.  This metadata is set with convienance methods: set_slack_link, set_slack_message_identifier, set_slack_data ... It is not clear to me if this metadata is actually used anywhere.', null=True),
        ),
        migrations.AlterField(
            model_name='accountnotification',
            name='statuses',
            field=models.JSONField(blank=True, default=notifications.models.get_default_statuses, help_text='A dictionary mapping notification channel names to the status of the message in each channel.  This is documented in greater detail on the BaseNotification model.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='cluster_alert',
            field=models.ForeignKey(blank=True, help_text='Associated cluster alert, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.clusteralert'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_sent_to',
            field=models.JSONField(blank=True, default=list, help_text="JSON list of user ID's the notification was sent to", null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.JSONField(blank=True, default=dict, help_text='Unused?', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='slack_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Slack metadata is used by slack notification messages.  This metadata is set with convienance methods: set_slack_link, set_slack_message_identifier, set_slack_data ... It is not clear to me if this metadata is actually used anywhere.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='statuses',
            field=models.JSONField(blank=True, default=notifications.models.get_default_statuses, help_text='A dictionary mapping notification channel names to the status of the message in each channel.  This is documented in greater detail on the BaseNotification model.', null=True),
        ),
    ]
