# Generated by Django 5.0.7 on 2025-02-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacovestoken",
            name="type",
            field=models.SmallIntegerField(
                choices=[(1, "Project"), (2, "Environment")]
            ),
        ),
    ]
