# Generated by Django 5.0.7 on 2025-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_alter_datacovestoken_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacovestoken',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
