# Generated by Django 3.2.6 on 2022-09-21 15:55

import autoslug.fields
from django.db import migrations
import users.models


def set_users_slug(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.slug = f"{user.email[:3]}-{user.id}"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_service_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from=users.models.user_slug,
                unique=True,
            ),
        ),
        migrations.RunPython(set_users_slug),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from=users.models.user_slug, unique=True
            ),
        ),
    ]
