# Generated by Django 3.2.6 on 2022-10-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20221013_1819'),
        ('users', '0003_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan'),
        ),
    ]
