# Generated by Django 3.2.6 on 2022-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trial_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
