# Generated by Django 3.2.6 on 2022-10-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221014_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='subscription_payload',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_requested_at',
            new_name='subscription_retrieved_at',
        ),
    ]
