# Generated by Django 3.2.6 on 2022-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221020_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='subscription_retrieved_at',
            new_name='subscription_updated_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
