# Generated by Django 3.2.6 on 2022-11-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221028_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='trial_ended_at',
            new_name='trial_ends_at',
        ),
    ]
