# Generated by Django 3.2.6 on 2022-11-15 18:49

import users.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_trial_ended_at_account_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='workers_execution_limit',
            field=models.JSONField(default=users.models.account.get_default_workers_execution_limit, null=True),
        ),
    ]
