# Generated by Django 3.2.6 on 2022-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_account_workers_execution_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approve_billing_events',
            field=models.BooleanField(default=True, help_text='Is approval required for billing events before they are informed?'),
        ),
    ]
