# Generated by Django 3.2.6 on 2022-12-29 20:17

import users.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_account_approve_billing_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notifications_enabled',
            field=models.JSONField(blank=True, default=users.models.account.get_default_notifications_enabled, null=True),
        ),
    ]
