# Generated by Django 3.2.16 on 2023-02-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_profile_files_from'),
        ('users', '0011_account_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedgroup',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='extendedgroup',
            name='role',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('account_admin', 'Account Admin'), ('project_developer', 'Project Developer'), ('project_viewer', 'Project Viewer'), ('environment_developer', 'Environment Developer'), ('environment_viewer', 'Environment Viewer')], max_length=30, null=True),
        ),
    ]
