# Generated by Django 3.2.16 on 2023-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230206_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cancelled_subscription',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
