# Generated by Django 3.2.16 on 2023-03-03 14:12

import users.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_account_cancelled_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='developer_licenses',
            field=models.PositiveIntegerField(default=0, help_text='Max number of developer licenses (users with access to at least one code-server pod), zero means infinite.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='workers_execution_limit',
            field=models.JSONField(default=users.models.account.get_default_workers_execution_limit, help_text='max execution seconds allowed per period at account level', null=True),
        ),
    ]
