# Generated by Django 3.2.16 on 2023-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230303_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedgroup',
            name='role',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('account_admin', 'Account Admin'), ('project_developer', 'Project Developer'), ('project_viewer', 'Project Viewer'), ('project_sysadmin', 'Project Sys Admin'), ('environment_developer', 'Environment Developer'), ('environment_viewer', 'Environment Viewer'), ('environment_sysadmin', 'Environment Sys Admin')], max_length=30, null=True),
        ),
    ]
