# Generated by Django 3.2.16 on 2023-07-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_extendedgroup_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedgroup',
            name='description',
        ),
    ]
