# Generated by Django 3.2.20 on 2023-11-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_extendedgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='variant',
            field=models.CharField(default='standard', max_length=32),
        ),
    ]
