# Generated by Django 3.2.20 on 2024-01-18 22:32

import autoslug.fields
import users.models.account
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_account_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=users.models.account.account_slug, unique=True),
        ),
    ]
