# Generated by Django 3.2.20 on 2024-02-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedgroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
