# Generated by Django 3.2.20 on 2024-02-05 15:34

from django.db import migrations


def create_name(extended_group):
    if extended_group.environment:
        return f"{extended_group.environment.name} ({extended_group.environment.slug}) {extended_group.get_role_display()}"
    if extended_group.project:
        return f"{extended_group.project.name} {extended_group.get_role_display()}"
    if extended_group.role:
        return f"{extended_group.account.name} {extended_group.get_role_display()}"
    else:
        return extended_group.group.name.replace(f"'{extended_group.account.slug}' ", "")

def add_name(apps, schema_editor):
    ExtendedGroup = apps.get_model('users', 'ExtendedGroup')
    
    for extended_group in ExtendedGroup.objects.all():
        extended_group.name = create_name(extended_group)
        extended_group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_extendedgroup_name'),
    ]

    operations = [
        migrations.RunPython(add_name)
    ]
