# Generated by Django 3.2.20 on 2024-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_extendedgroup_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cancelled_subscription',
            field=models.JSONField(blank=True, default=dict, help_text='The cancelled subscription object, if it has been cancelled', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription',
            field=models.JSONField(blank=True, default=dict, help_text='This subscription object comes from Stripe.', null=True),
        ),
        migrations.AlterField(
            model_name='extendedgroup',
            name='identity_groups',
            field=models.JSONField(blank=True, default=list, help_text='A list of groups from the external identity source which will map to this group with the given role.', null=True),
        ),
    ]
