# Generated by Django 5.0.7 on 2024-08-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20240701_2118"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="setup_enabled",
            field=models.BooleanField(null=True),
        ),
    ]
