# Generated by Django 5.0.7 on 2024-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_user_setup_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedgroup",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("account_admin", "Account Admin"),
                    ("project_developer", "Project Developer"),
                    ("project_viewer", "Project Viewer"),
                    ("project_sysadmin", "Project Sys Admin"),
                    ("project_admin", "Project Admin"),
                    ("environment_developer", "Environment Developer"),
                    ("environment_viewer", "Environment Viewer"),
                    ("environment_sysadmin", "Environment Sys Admin"),
                    ("environment_admin", "Environment Admin"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
