# Generated by Django 3.2.16 on 2023-03-03 18:44

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0076_update_account_permissions"),
        ("taggit", "0005_auto_20220424_2025"),
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="secret",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
        ),
        migrations.AlterField(
            model_name="secret",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("project", "slug"), name="Project and slug uniqueness"
            ),
        ),
    ]
