# Generated by Django 3.2.20 on 2024-07-10 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0105_auto_20240701_2118"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credentials", "0002_auto_20230303_1844"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="secret",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="projects.environment",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="services",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="secret",
            name="sharing_scope",
            field=models.CharField(
                choices=[
                    ("project", "Shared within a project"),
                    ("environment", "Shared within an environment"),
                ],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="secret",
            name="value_format",
            field=models.CharField(
                choices=[
                    ("plain_text", "Plain text"),
                    ("dict", "Key-value string pairs"),
                    ("json", "Raw JSON"),
                ],
                default="plain_text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="secret",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_secrets",
                to="users.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="secret",
            name="slug",
            field=models.CharField(max_length=200),
        ),
    ]
