# Generated by Django 5.0.7 on 2024-08-12 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0003_auto_20240710_1542"),
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="secret",
            index=models.Index(
                fields=["sharing_scope", "project_id", "slug"],
                name="credentials_sharing_c78bb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="secret",
            index=models.Index(
                fields=["sharing_scope", "project_id", "environment_id", "slug"],
                name="credentials_sharing_88ede7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="secret",
            index=models.Index(
                fields=["sharing_scope", "project_id", "users", "services", "slug"],
                name="credentials_sharing_c9a788_idx",
            ),
        ),
    ]
