# Generated by Django 5.0.7 on 2024-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0004_secret_credentials_sharing_c78bb7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="accessed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="secret",
            name="backend",
            field=models.CharField(
                choices=[
                    ("datacoves", "Datacoves"),
                    ("aws_secrets_manager", "AWS Secrets Manager"),
                ],
                default="datacoves",
                max_length=50,
            ),
        ),
    ]
