# Generated by Django 5.0.7 on 2024-11-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_secret_accessed_at_secret_backend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='name',
        ),
    ]
