# Generated by Django 3.2.6 on 2022-03-03 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credentials', to='projects.connection'),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credentials', to='projects.environment'),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecredential',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_credentials', to='projects.connection'),
        ),
        migrations.AddField(
            model_name='servicecredential',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_credentials', to='projects.environment'),
        ),
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.version'),
        ),
        migrations.AddField(
            model_name='project',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.account'),
        ),
        migrations.AddField(
            model_name='project',
            name='deploy_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.sshkey'),
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.repository'),
        ),
        migrations.AddField(
            model_name='environment',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='clusters.cluster'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='environment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='projects.release'),
        ),
        migrations.AddField(
            model_name='environment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='projects.version'),
        ),
        migrations.AddField(
            model_name='connection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='userrepository',
            constraint=models.UniqueConstraint(fields=('user', 'repository'), name='User repository uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='usercredential',
            constraint=models.UniqueConstraint(fields=('user', 'environment', 'used_on'), name='User credential uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='servicecredential',
            constraint=models.UniqueConstraint(fields=('environment', 'service', 'target'), name='Environment service credential uniqueness'),
        ),
    ]
