# Generated by Django 3.2.6 on 2022-03-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredential',
            name='service',
            field=models.CharField(choices=[('airbyte', 'Airbyte'), ('airflow', 'Airflow'), ('code-server', 'Code-Server'), ('dbt-docs', 'Dbt-Docs'), ('metabase', 'Metabase'), ('superset', 'Superset')], max_length=50),
        ),
    ]
