# Generated by Django 3.2.6 on 2022-03-18 17:53

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_servicecredential_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='metabase_db_config',
            new_name='superset_db_config',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='metabase_version',
            new_name='superset_version',
        ),
        migrations.AddField(
            model_name='environment',
            name='superset_keystore_config',
            field=core.fields.EncryptedJSONField(default=dict, editable=True),
        ),
        migrations.AddField(
            model_name='release',
            name='superset_images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='service',
            field=models.CharField(choices=[('airbyte', 'Airbyte'), ('airflow', 'Airflow'), ('code-server', 'Code-Server'), ('dbt-docs', 'Dbt-Docs'), ('superset', 'Superset')], max_length=50),
        ),
    ]
