# Generated by Django 3.2.6 on 2022-03-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220318_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='superset_db_config',
            new_name='superset_config',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='superset_keystore_config',
        ),
    ]
