# Generated by Django 3.2.6 on 2022-03-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220318_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='dbt_docs_branch',
            field=models.CharField(default='dbt-docs', max_length=130),
        ),
        migrations.AddField(
            model_name='project',
            name='dbt_docs_branch',
            field=models.CharField(default='dbt-docs', max_length=130),
        ),
        migrations.AlterField(
            model_name='environment',
            name='release_branch',
            field=models.CharField(default='main', max_length=130),
        ),
    ]
