# Generated by Django 3.2.6 on 2022-04-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220329_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='airbyte_db_config',
            new_name='airbyte_config',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='airbyte_logs_config',
        ),
    ]
