# Generated by Django 3.2.6 on 2022-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220404_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='airbyte_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='airflow_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='superset_chart',
            field=models.JSONField(default=dict),
        ),
    ]
