# Generated by Django 3.2.6 on 2022-04-12 14:05

import core.fields
from django.db import migrations
import projects.models.environment


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220407_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='docker_config',
            field=core.fields.EncryptedJSONField(default=projects.models.environment.default_docker_config, editable=True),
        ),
    ]
