# Generated by Django 3.2.6 on 2022-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_environment_docker_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('snowflake', 'Snowflake'), ('redshift', 'Redshift'), ('bigquery', 'BigQuery')], max_length=60),
        ),
    ]
