# Generated by Django 3.2.6 on 2022-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_connection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="sync",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="version",
            name="code_server_extensions",
            field=models.JSONField(default=""),
        ),
        migrations.AlterField(
            model_name="version",
            name="code_server_libraries",
            field=models.JSONField(default=""),
        ),
    ]
