# Generated by Django 3.2.6 on 2022-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220506_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='docker_registry',
            field=models.CharField(blank=True, max_length=253),
        ),
    ]
