# Generated by Django 3.2.6 on 2022-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_environment_docker_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='version',
        ),
        migrations.RemoveField(
            model_name='release',
            name='version',
        ),
        migrations.AddField(
            model_name='release',
            name='airbyte_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='release',
            name='airflow_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='release',
            name='code_server_extensions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='code_server_libraries',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='code_server_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='release',
            name='dbt_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='release',
            name='superset_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
