# Generated by Django 3.2.6 on 2022-05-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220518_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='channels',
            field=models.JSONField(default=list),
        ),
    ]
