# Generated by Django 3.2.6 on 2022-05-20 12:13

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_release_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='docker_config_secret_name',
            field=models.CharField(blank=True, default='docker-config-datacovesprivate', max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deploy_credentials',
            field=core.fields.EncryptedJSONField(default=dict, editable=True),
        ),
    ]
