# Generated by Django 3.2.6 on 2022-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20220520_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='last_sync_unmet_preconditions',
            field=models.JSONField(default=dict),
        ),
    ]
