# Generated by Django 3.2.6 on 2022-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_environment_last_sync_unmet_preconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='last_sync_unmet_preconditions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
