# Generated by Django 3.2.6 on 2022-05-31 19:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_environment_last_sync_unmet_preconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='airbyte_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='airflow_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='elastic_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='superset_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deploy_credentials',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='connection_overrides',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='connection_overrides',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
