# Generated by Django 3.2.6 on 2022-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20220531_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='release_branch',
        ),
    ]
