# Generated by Django 3.2.6 on 2022-06-03 17:05

import core.fields
from django.db import migrations
import projects.models.environment


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_environment_release_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='docker_config',
            field=core.fields.EncryptedJSONField(blank=True, default=projects.models.environment.default_docker_config, editable=True, null=True),
        ),
    ]
