# Generated by Django 3.2.6 on 2022-06-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_environment_docker_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='elastic_config',
        ),
    ]
