# Generated by Django 3.2.6 on 2022-06-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_service_account'),
        ('projects', '0021_remove_environment_elastic_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=130)),
                ('required_fieldsets', models.JSONField(blank=True, default=list, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_types', to='users.account')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='projects.connectiontype'),
        ),
        migrations.AddConstraint(
            model_name='connectiontype',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='Connection type account name uniqueness'),
        ),
    ]
