# Generated by Django 3.2.6 on 2022-06-08 21:08

from django.db import migrations


def account_connection_types(account, apps):
    ConnectionType = apps.get_model("projects", "ConnectionType")

    ConnectionType.objects.update_or_create(
        name="snowflake",
        account=account,
        defaults={
            "required_fieldsets": [
                [
                    "account",
                    "username",
                    "password",
                    "database",
                    "warehouse",
                    "schema",
                ]
            ]
        },
    )

    ConnectionType.objects.update_or_create(
        name="redshift",
        account=account,
        defaults={
            "required_fieldsets": [
                ["host", "port", "username", "password", "database", "schema"]
            ]
        },
    )

    ConnectionType.objects.update_or_create(
        name="bigquery",
        account=account,
        defaults={
            "required_fieldsets": [
                [
                    "project",
                    "dataset",
                    "refresh_token",
                    "client_id",
                    "client_secret",
                    "token_uri",
                ]
            ]
        },
    )


def create_connection_types(apps, schema_editor):
    Account = apps.get_model("users", "Account")
    for account in Account.objects.all():
        account_connection_types(account, apps)

    Connection = apps.get_model("projects", "Connection")
    ConnectionType = apps.get_model("projects", "ConnectionType")
    for connection in Connection.objects.all():
        connection.type_id = ConnectionType.objects.get(
            account=connection.project.account, name=connection.type
        )
        connection.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_auto_20220608_2108"),
    ]

    operations = [
        migrations.RunPython(create_connection_types),
    ]
