# Generated by Django 3.2.6 on 2022-06-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20220608_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='type',
        ),
        migrations.AlterField(
            model_name='connection',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='projects.connectiontype'),
        ),
    ]
