# Generated by Django 3.2.6 on 2022-06-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20220608_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='type_id',
            new_name='type',
        ),
    ]
