# Generated by Django 3.2.6 on 2022-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_rename_type_id_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='for_users',
            field=models.BooleanField(default=True),
        ),
    ]
