# Generated by Django 3.2.6 on 2022-06-14 19:50

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_connection_for_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshkey",
            name="private",
            field=core.fields.EncryptedTextField(editable=True),
        ),
    ]
