# Generated by Django 3.2.6 on 2022-06-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_sshkey_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.sshkey'),
        ),
    ]
