# Generated by Django 3.2.6 on 2022-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_project_deploy_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
