# Generated by Django 3.2.6 on 2022-06-27 22:07

import core.fields
from django.db import migrations, models
import projects.models.environment


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='internal_services',
            field=models.JSONField(default=projects.models.environment.default_internal_services),
        ),
        migrations.AddField(
            model_name='environment',
            name='minio_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='minio_chart',
            field=models.JSONField(default=dict),
        ),
    ]
