# Generated by Django 3.2.6 on 2022-06-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='dbt_home_path',
            field=models.CharField(blank=True, default='transform', max_length=4096),
        ),
        migrations.AlterField(
            model_name='environment',
            name='dbt_profiles_dir',
            field=models.CharField(blank=True, default='automate', max_length=4096),
        ),
    ]
