# Generated by Django 3.2.6 on 2022-06-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20220627_2207'),
        ('projects', '0030_auto_20220627_2307'),
    ]

    operations = [
    ]
