# Generated by Django 3.2.6 on 2022-06-30 18:51

import core.fields
from django.db import migrations
import projects.models.environment


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_merge_0030_auto_20220627_2207_0030_auto_20220627_2307"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="code_server_config",
            field=core.fields.EncryptedJSONField(
                blank=True, default=dict, editable=True, null=True
            ),
        ),
    ]
