# Generated by Django 3.2.6 on 2022-07-07 17:24

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0032_environment_code_server_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_type', models.CharField(choices=[('dsa', 'dsa'), ('rsa', 'rsa')], default='rsa', max_length=20)),
                ('private', core.fields.EncryptedTextField(editable=True)),
                ('public', models.TextField()),
                ('for_users', models.BooleanField(default=True)),
                ('generated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SSL key',
            },
        ),
        migrations.RemoveConstraint(
            model_name='usercredential',
            name='User credential uniqueness',
        ),
        migrations.AddField(
            model_name='sshkey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sshkey',
            name='for_users',
            field=models.BooleanField(default=True, help_text="If for users, it can't be used on services."),
        ),
        migrations.AddField(
            model_name='sshkey',
            name='generated',
            field=models.BooleanField(default=True, help_text='If not generated, it means the user provided it.'),
        ),
        migrations.AddConstraint(
            model_name='usercredential',
            constraint=models.UniqueConstraint(fields=('user', 'environment', 'connection'), name='User credential uniqueness'),
        ),
        migrations.AddField(
            model_name='sslkey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecredential',
            name='ssl_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_credentials', to='projects.sslkey'),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='ssl_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credentials', to='projects.sslkey'),
        ),
    ]
