# Generated by Django 3.2.6 on 2022-07-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0002_sqlhook'),
        ('projects', '0033_auto_20220707_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='user_credentials_save_hook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codegen.sqlhook'),
        ),
    ]
