# Generated by Django 3.2.6 on 2022-07-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_connection_user_credentials_save_hook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='user_credentials_save_hook',
        ),
    ]
