# Generated by Django 3.2.6 on 2022-07-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_service_account'),
        ('projects', '0034_connection_user_credentials_save_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontype',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_types', to='users.account'),
        ),
    ]
