# Generated by Django 3.2.6 on 2022-07-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0004_alter_template_context_type'),
        ('projects', '0035_remove_connection_user_credentials_save_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='dbt_profiles_yml_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codegen.template'),
        ),
    ]
