# Generated by Django 3.2.6 on 2022-07-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_connectiontype_account'),
        ('projects', '0035_remove_connection_user_credentials_save_hook'),
    ]

    operations = [
    ]
