# Generated by Django 3.2.6 on 2022-07-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_environment_dbt_profiles_yml_template'),
        ('projects', '0036_merge_20220720_1756'),
    ]

    operations = [
    ]
