# Generated by Django 3.2.6 on 2022-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_merge_20220721_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='name',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
