# Generated by Django 3.2.6 on 2022-07-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_usercredential_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercredential',
            name='User credential uniqueness',
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='name',
            field=models.CharField(default='dev', max_length=130),
        ),
        migrations.AddConstraint(
            model_name='usercredential',
            constraint=models.UniqueConstraint(fields=('user', 'environment', 'name'), name='User credential uniqueness'),
        ),
    ]
