# Generated by Django 3.2.6 on 2022-07-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0006_alter_template_context_type'),
        ('projects', '0039_auto_20220721_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='dbt_profiles_yml_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_dbt_profiles', to='codegen.template'),
        ),
    ]
