# Generated by Django 3.2.6 on 2022-07-22 14:45

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


def create_default_profile(apps, schema_editor):
    Profile = apps.get_model("projects", "Profile")
    Profile.objects.create(name="Default", slug="default")


class Migration(migrations.Migration):

    dependencies = [
        ("codegen", "0006_alter_template_context_type"),
        ("projects", "0040_alter_environment_dbt_profiles_yml_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("python_requirements", models.TextField(blank=True, null=True)),
                ("dbt_sync", models.BooleanField(default=True)),
                ("dbt_local_docs", models.BooleanField(default=True)),
                ("mount_ssl_keys", models.BooleanField(default=True)),
                ("mount_ssh_keys", models.BooleanField(default=True)),
                ("mount_api_token", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_profile),
        migrations.RemoveField(
            model_name="environment",
            name="code_server_config",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="dbt_profiles_yml_template",
        ),
        migrations.CreateModel(
            name="ProfileFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("mount_path", models.CharField(max_length=32, unique=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.profile",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codegen.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="environment",
            name="code_server_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.profile",
            ),
            preserve_default=False,
        ),
    ]
