# Generated by Django 3.2.6 on 2022-07-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0007_auto_20220722_1510'),
        ('users', '0002_user_is_service_account'),
        ('projects', '0041_auto_20220722_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Global profiles are available on all accounts'),
        ),
        migrations.AlterField(
            model_name='profilefile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.profile'),
        ),
        migrations.AlterField(
            model_name='profilefile',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_files', to='codegen.template'),
        ),
    ]
