# Generated by Django 3.2.6 on 2022-07-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20220722_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='code_server_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.profile'),
        ),
    ]
