# Generated by Django 3.2.6 on 2022-07-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_environment_code_server_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_global',
        ),
        migrations.AlterField(
            model_name='connectiontype',
            name='name',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
