# Generated by Django 3.2.6 on 2022-07-29 16:53

from django.db import migrations, models


def associate_new_permissions(apps, schema_editor):
    from django.conf import settings

    Account = apps.get_model("users", "Account")
    Project = apps.get_model("projects", "Project")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get_for_model(Account)

    for project in Project.objects.all():
        for resource in settings.WORKBENCH_RESOURCES:
            w_name = f"{project.account.slug}:{project.slug}|{resource}|{settings.ACTION_WRITE}"
            r_name = f"{project.account.slug}:{project.slug}|{resource}|{settings.ACTION_READ}"
            Permission.objects.get_or_create(
                name=w_name,
                content_type=content_type,
                defaults={"codename": w_name[:100]},
            )
            Permission.objects.get_or_create(
                name=r_name,
                content_type=content_type,
                defaults={"codename": r_name[:100]},
            )

        permissions = Permission.objects.filter(
            name__contains=f":{project.slug}|workbench:local-dbt-docs"
        )
        for ext_group in project.extendedgroup_set.filter(role="project_developer"):
            for permission in permissions:
                ext_group.group.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0044_auto_20220722_1922"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecredential",
            name="service",
            field=models.CharField(
                choices=[
                    ("airbyte", "Airbyte"),
                    ("airflow", "Airflow"),
                    ("code-server", "Code-Server"),
                    ("dbt-docs", "Dbt-Docs"),
                    ("local-dbt-docs", "Local-Dbt-Docs"),
                    ("superset", "Superset"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(associate_new_permissions),
    ]
