# Generated by Django 3.2.6 on 2022-08-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_alter_servicecredential_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clone_repository',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vscode_extensions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profilefile',
            name='execute',
            field=models.BooleanField(default=False, help_text='Specifies if file should be executed, requires shebang set on file'),
        ),
        migrations.AddField(
            model_name='profilefile',
            name='override_existent',
            field=models.BooleanField(default=False),
        ),
    ]
