# Generated by Django 3.2.6 on 2022-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20220802_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrepository',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
