# Generated by Django 3.2.6 on 2022-08-03 20:44

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20220802_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='pomerium_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vscode_extensions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
