# Generated by Django 3.2.6 on 2022-08-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20220803_2044'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='Project and name uniqueness'),
        ),
    ]
