# Generated by Django 3.2.6 on 2022-08-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_connection_project and name uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicecredential',
            name='Environment service credential uniqueness',
        ),
        migrations.RenameField(
            model_name='servicecredential',
            old_name='target',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='servicecredential',
            constraint=models.UniqueConstraint(fields=('environment', 'service', 'name'), name='Environment service credential uniqueness'),
        ),
    ]
