# Generated by Django 3.2.6 on 2022-08-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20220812_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshkey',
            name='for_users',
        ),
        migrations.RemoveField(
            model_name='sslkey',
            name='for_users',
        ),
        migrations.AddField(
            model_name='servicecredential',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sshkey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_keys', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sslkey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_keys', to='projects.project'),
        ),
    ]
