# Generated by Django 3.2.6 on 2022-08-18 11:56

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20220815_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefile',
            name='mount_path',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profilefile',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profilefile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AddConstraint(
            model_name='profilefile',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='Profile file name uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='profilefile',
            constraint=models.UniqueConstraint(fields=('profile', 'slug'), name='Profile file slug uniqueness'),
        ),
        migrations.AddConstraint(
            model_name='profilefile',
            constraint=models.UniqueConstraint(fields=('profile', 'mount_path'), name='Profile file mount path uniqueness'),
        ),
    ]
