# Generated by Django 3.2.6 on 2022-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20220818_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefile',
            name='mount_path',
            field=models.CharField(max_length=250),
        ),
    ]
