# Generated by Django 3.2.6 on 2022-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20220818_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dbt_docs_branch',
        ),
        migrations.AddField(
            model_name='project',
            name='ci_home_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ci_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'Gitlab'), ('bamboo', 'Bamboo'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI')], max_length=50, null=True),
        ),
    ]
