# Generated by Django 3.2.6 on 2022-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20220822_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ci_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'Gitlab'), ('bamboo', 'Bamboo'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
