# Generated by Django 3.2.6 on 2022-08-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_alter_profilefile_mount_path'),
        ('projects', '0054_auto_20220822_1610'),
    ]

    operations = [
    ]
