# Generated by Django 3.2.6 on 2022-08-26 15:07

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_merge_20220826_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='dbt_docs_branch',
        ),
        migrations.AddField(
            model_name='environment',
            name='dbt_docs_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
