# Generated by Django 3.2.6 on 2022-08-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0056_auto_20220826_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_server_active', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userenvironment',
            constraint=models.UniqueConstraint(fields=('environment', 'user'), name='Environment user uniqueness'),
        ),
    ]
