# Generated by Django 3.2.6 on 2022-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20220826_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='code_server_access',
            field=models.CharField(choices=[('private', 'private'), ('authenticated', 'authenticated'), ('public', 'public')], default='private', help_text='Who can access code-server? Change with caution as this configuration may expose sensitive information.', max_length=50),
        ),
        migrations.AddField(
            model_name='userenvironment',
            name='code_server_last_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
