# Generated by Django 3.2.6 on 2022-08-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20220829_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='services',
            field=models.JSONField(blank=True, default=dict, help_text="Dict of http services listening on code server pod, i.e. 'django': {'port': 3000, 'access': 'private'}", null=True),
        ),
        migrations.AlterField(
            model_name='userenvironment',
            name='code_server_last_shared_at',
            field=models.DateTimeField(blank=True, help_text='For security reasons, access will be changed back to private after 2 hours elapsed from this datetime', null=True),
        ),
    ]
