# Generated by Django 3.2.6 on 2022-08-31 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0059_auto_20220829_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='code_server_share_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userenvironment',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_environments', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='userenvironment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_environments', to=settings.AUTH_USER_MODEL),
        ),
    ]
