# Generated by Django 3.2.6 on 2022-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20220831_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Settings propagated to all environment settings. Avoid reading this field, instead, read environment settings.', null=True),
        ),
    ]
