# Generated by Django 3.2.6 on 2022-09-05 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20220905_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='code_server_restarted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
