# Generated by Django 3.2.6 on 2022-09-09 16:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_userenvironment_code_server_restarted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='snowflake', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectiontype',
            name='name',
            field=models.CharField(max_length=130),
        ),
    ]
