# Generated by Django 3.2.6 on 2022-09-12 12:31

from django.db import migrations, models
import django.db.models.deletion
import projects.models.environment


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0013_auto_20220728_1450'),
        ('projects', '0063_auto_20220909_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='cluster',
            field=models.ForeignKey(default=projects.models.environment.default_cluster, on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='clusters.cluster'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='release',
            field=models.ForeignKey(default=projects.models.environment.default_release, on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='projects.release'),
        ),
    ]
