# Generated by Django 3.2.6 on 2022-09-12 13:58

from django.db import migrations, models
import django.db.models.deletion
import projects.models.environment


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20220912_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='code_server_profile',
            field=models.ForeignKey(default=projects.models.environment.default_profile, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.profile'),
        ),
    ]
