# Generated by Django 3.2.6 on 2022-09-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_alter_environment_code_server_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_user',
            field=models.CharField(choices=[('provided', 'User provided'), ('email_username', "Inferred from email's username")], default='provided', max_length=20),
        ),
    ]
