# Generated by Django 3.2.6 on 2022-09-28 16:11

import autoslug.fields
import django.db.models.deletion
import projects.models.connection
import projects.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0066_connection_connection_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('airbyte', 'Airbyte'), ('airflow', 'Airflow'), ('code-server', 'Code-Server'), ('dbt-docs', 'Dbt-Docs'), ('local-dbt-docs', 'Local-Dbt-Docs'), ('superset', 'Superset')], max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Specific configuration for the service that uses the integration', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='connectiontype',
            name='Connection type account name uniqueness',
        ),
        migrations.AlterField(
            model_name='connectiontype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=projects.models.connection.connectiontype_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=projects.models.profile.profile_slug, unique=True),
        ),
        migrations.AddField(
            model_name='environmentintegration',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='projects.environment'),
        ),
        migrations.AddField(
            model_name='environmentintegration',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='integrations.integration'),
        ),
    ]
