# Generated by Django 3.2.6 on 2022-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20220928_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='quotas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
