# Generated by Django 3.2.6 on 2022-11-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_environment_quotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='last_sync_unmet_preconditions',
        ),
    ]
