# Generated by Django 3.2.6 on 2022-11-10 04:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_remove_environment_last_sync_unmet_preconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPodCreationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request', models.JSONField(blank=True, default=dict, null=True)),
                ('response', models.JSONField(blank=True, default=dict, null=True)),
                ('request_uid', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('namespace', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
