# Generated by Django 3.2.6 on 2022-12-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_blockedpodcreationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='code_server_profile',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='python_requirements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vscode_extensions',
        ),
        migrations.AlterField(
            model_name='profile',
            name='clone_repository',
            field=models.BooleanField(default=True, help_text='When enabled, the project git repository gets cloned automatically'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dbt_local_docs',
            field=models.BooleanField(default=True, help_text='If enabled, a web server is launched to serve local dbt docs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dbt_sync',
            field=models.BooleanField(default=True, help_text='If enabled, dbt osmosis gets installed as a requirement of the datacoves power user extension'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mount_api_token',
            field=models.BooleanField(default=True, help_text='If enabled, an api_token is mounted as environment variable'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mount_ssh_keys',
            field=models.BooleanField(default=True, help_text='When enabled, ssl keys are mounted under /config/.ssh/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mount_ssl_keys',
            field=models.BooleanField(default=True, help_text='When enabled, ssl keys are mounted under /config/.ssl/'),
        ),
        migrations.AlterField(
            model_name='profilefile',
            name='override_existent',
            field=models.BooleanField(default=False, help_text='When enabled, if a file is found, it will be overwritten.'),
        ),
        migrations.CreateModel(
            name='ProfileImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_requirements', models.JSONField(blank=True, default=list, help_text='List of python libs to be used in both airflow and code server images, e.g. ["Django==3.2.6"]', null=True)),
                ('airflow_requirements', models.JSONField(blank=True, default=list, help_text='List of python libs to be used in airflow images, e.g. ["Django==3.2.6"]', null=True)),
                ('code_server_requirements', models.JSONField(blank=True, default=list, help_text='List of python libs to be used in code server images, e.g. ["Django==3.2.6"]', null=True)),
                ('code_server_extensions', models.JSONField(blank=True, default=list, help_text='List of urls to vscode extensions that will be downloaded, unzipped and installed.', null=True)),
                ('images_status', models.JSONField(blank=True, default=dict, help_text='A dictionary mapping docker image names to their build status.', null=True)),
                ('images', models.JSONField(blank=True, default=dict, help_text="A dictionary mapping docker image names to tags (versions). if empty, it means the build process didn't complete", null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_sets', to='projects.profile')),
                ('release', models.ForeignKey(help_text='Release that contains images from where new images will be based.', on_delete=django.db.models.deletion.PROTECT, to='projects.release')),
            ],
        ),
    ]
