# Generated by Django 3.2.16 on 2023-01-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_auto_20221228_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshkey',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sslkey',
            name='project',
        ),
        migrations.AddField(
            model_name='sshkey',
            name='usage',
            field=models.CharField(choices=[('user', 'User'), ('project', 'Project')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='sslkey',
            name='usage',
            field=models.CharField(choices=[('user', 'User'), ('project', 'Project')], default='user', max_length=20),
        ),
    ]
