# Generated by Django 3.2.16 on 2023-02-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20230118_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='files_from',
            field=models.ForeignKey(blank=True, help_text='Profile used as starting point for files configuration. Files added to current profile are appended to the base profile files list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.profile'),
        ),
    ]
