# Generated by Django 3.2.16 on 2023-02-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codegen", "0016_auto_20230206_1930"),
        ("projects", "0073_profile_files_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="connection_user_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="codegen.template",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="connection_user",
            field=models.CharField(
                choices=[
                    ("provided", "User provided"),
                    ("email_username", "Inferred from email's username"),
                    ("template", "Inferred from user info using a custom template"),
                ],
                default="provided",
                max_length=20,
            ),
        ),
    ]
