# Generated by Django 3.2.16 on 2023-02-23 18:35

import core.fields
import django.db.models.deletion
from django.db import migrations, models


def update_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    for permission in Permission.objects.filter(name__icontains="admin:connections|"):
        permission.name = permission.name.replace(
            "admin:connections", "admin:connectiontemplates"
        )
        permission.save()


class Migration(migrations.Migration):
    dependencies = [
        ("codegen", "0017_alter_template_format"),
        ("projects", "0074_auto_20230222_1322"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Connection",
            new_name="ConnectionTemplate",
        ),
        migrations.RenameField(
            model_name="servicecredential",
            old_name="connection",
            new_name="connection_template",
        ),
        migrations.RenameField(
            model_name="usercredential",
            old_name="connection",
            new_name="connection_template",
        ),
        migrations.AlterField(
            model_name="connectiontemplate",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_templates",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="connectiontemplate",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_templates",
                to="projects.connectiontype",
            ),
        ),
        migrations.RunPython(update_permissions),
    ]
