# Generated by Django 3.2.16 on 2023-02-23 18:35

from django.conf import settings
from django.db import migrations


def create_permissions(apps, account):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type = ContentType.objects.get(app_label="users", model="account")
    for resource in settings.ACCOUNT_RESOURCES:
        w_name = f"{account.slug}|{resource}|{settings.ACTION_WRITE}"
        r_name = f"{account.slug}|{resource}|{settings.ACTION_READ}"
        Permission.objects.get_or_create(
            name=w_name,
            content_type=content_type,
            defaults={"codename": w_name[:100]},
        )
        Permission.objects.get_or_create(
            name=r_name,
            content_type=content_type,
            defaults={"codename": r_name[:100]},
        )


def reassign_account_groups_permissions(apps, account):
    ExtendedGroup = apps.get_model("users", "ExtendedGroup")
    Permission = apps.get_model("auth", "Permission")
    ext_group = ExtendedGroup.objects.get(account=account, role="account_admin")
    if ext_group:
        for permission in Permission.objects.filter(
            name__startswith=f"{account.slug}|"
        ):
            ext_group.group.permissions.add(permission)


def update_account_permissions(apps, schema_editor):
    Account = apps.get_model("users", "Account")
    for account in Account.objects.all():
        create_permissions(apps, account)
        reassign_account_groups_permissions(apps, account)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0075_auto_20230223_1835"),
    ]

    operations = [
        migrations.RunPython(update_account_permissions),
    ]
