# Generated by Django 3.2.16 on 2023-03-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_update_account_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenvironment',
            name='services',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of http services listening on code server pod, i.e. {"django": {"port": 3000, "access": "private", "websockets": "true"}}', null=True),
        ),
    ]
