# Generated by Django 3.2.16 on 2023-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_alter_userenvironment_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='observability_images',
            field=models.JSONField(default=list),
        ),
    ]
