# Generated by Django 3.2.16 on 2023-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_release_observability_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='update_strategy',
            field=models.CharField(choices=[('latest', 'Update to latest'), ('freezed', 'Freeze release'), ('minor', 'Update to latest minor patch'), ('major', 'Update to latest major patch')], default='freezed', max_length=10),
        ),
    ]
