# Generated by Django 3.2.16 on 2023-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_environment_update_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='core_images',
            field=models.JSONField(default=list),
        ),
    ]
