# Generated by Django 3.2.16 on 2023-04-20 13:55

import autoslug.fields
from django.db import migrations
import projects.models.profile


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0081_update_account_permissions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="profilefile",
            name="Profile file name uniqueness",
        ),
        migrations.RemoveConstraint(
            model_name="profilefile",
            name="Profile file mount path uniqueness",
        ),
        migrations.RemoveField(
            model_name="profilefile",
            name="name",
        ),
        migrations.AlterField(
            model_name="profilefile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from=projects.models.profile.profile_file_slug
            ),
        ),
    ]
