# Generated by Django 3.2.16 on 2023-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_auto_20230420_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='release_profile',
            field=models.CharField(choices=[('dbt-snowflake', 'dbt-snowflake'), ('dbt-redshift', 'dbt-redshift'), ('dbt-bigquery', 'dbt-bigquery'), ('dbt-databricks', 'dbt-databricks')], default='dbt-snowflake', max_length=50),
        ),
        migrations.AddField(
            model_name='profileimageset',
            name='build_airflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileimageset',
            name='build_ci_airflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileimageset',
            name='build_ci_basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileimageset',
            name='build_code_server',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profileimageset',
            name='build_dbt_osmosis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profileimageset',
            name='ci_requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of python libs to be used in ci images, e.g. ["Django==3.2.6"]', null=True),
        ),
    ]
