# Generated by Django 3.2.16 on 2023-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_auto_20230425_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
