# Generated by Django 3.2.16 on 2023-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_auto_20230425_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimageset',
            old_name='build_dbt_osmosis',
            new_name='build_dbt_core_interface',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dbt_sync',
            field=models.BooleanField(default=True, help_text='If enabled, dbt core interface gets installed as a requirement of the datacoves power user extension'),
        ),
    ]
