# Generated by Django 3.2.16 on 2023-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_alter_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='deprecated',
            field=models.JSONField(default=dict),
        ),
    ]
