# Generated by Django 3.2.16 on 2023-08-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_release_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='dbt_home_path',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
