# Generated by Django 3.2.16 on 2023-09-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20230703_2212'),
        ('projects', '0086_alter_environment_dbt_home_path'),
    ]

    operations = [
    ]
