# Generated by Django 3.2.16 on 2023-10-18 13:38

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_merge_20230901_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='variables',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='variables',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='userenvironment',
            name='variables',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
