# Generated by Django 3.2.20 on 2023-11-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_auto_20231017_1950'),
        ('projects', '0088_auto_20231018_1338'),
    ]

    operations = [
    ]
