# Generated by Django 3.2.20 on 2023-11-02 23:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_auto_20231017_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='code_server_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
