# Generated by Django 3.2.20 on 2023-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_environment_code_server_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='profile_flags',
            field=models.JSONField(default=dict),
        ),
    ]
