# Generated by Django 3.2.20 on 2023-11-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_merge_0088_auto_20231017_1950_0088_auto_20231018_1338'),
        ('projects', '0090_release_profile_flags'),
    ]

    operations = [
    ]
