# Generated by Django 3.2.20 on 2023-12-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_merge_20231116_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userenvironment',
            old_name='services',
            new_name='exposures',
        ),
    ]
