# Generated by Django 3.2.20 on 2023-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_rename_services_userenvironment_exposures'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='services',
            field=models.JSONField(blank=True, default=dict, help_text='Dict to handle the state of services at user level and unmet preconditions if found.', null=True),
        ),
    ]
