# Generated by Django 3.2.16 on 2024-01-12 18:35

from django.conf import settings
from django.db import migrations


def update_or_create_dbt_api_permissions(apps, schema_editor):
    Environment = apps.get_model("projects", "Environment")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get(app_label="users", model="account")

    for env in Environment.objects.all():
        for resource in settings.DBT_API_RESOURCES:
            name = resource.format(
                cluster_domain=env.cluster.domain, env_slug=env.slug
            )
            Permission.objects.get_or_create(
                name=name,
                content_type=content_type,
                defaults={"codename": name[:100]},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0093_userenvironment_services"),
    ]

    operations = [
        migrations.RunPython(update_or_create_dbt_api_permissions),
    ]
