# Generated by Django 3.2.20 on 2024-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_update_dbt_api_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefile',
            name='override_existent',
            field=models.BooleanField(default=True, help_text='When enabled, if a file is found, it will be overwritten.'),
        ),
    ]
