# Generated by Django 3.2.20 on 2024-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_alter_profilefile_override_existent'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='promtail_chart',
            field=models.JSONField(default=dict),
        ),
    ]
