# Generated by Django 3.2.20 on 2024-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_release_promtail_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='dbt_profiles_dir',
            field=models.CharField(blank=True, default='automate/dbt', max_length=4096),
        ),
    ]
