# Generated by Django 3.2.20 on 2024-04-08 17:10

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_release_promtail_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='grafana_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentintegration',
            name='service',
            field=models.CharField(choices=[('airbyte', 'Airbyte'), ('airflow', 'Airflow'), ('code-server', 'Code-Server'), ('dbt-docs', 'Dbt-Docs'), ('grafana', 'Grafana'), ('local-dbt-docs', 'Local-Dbt-Docs'), ('superset', 'Superset')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='service',
            field=models.CharField(choices=[('airbyte', 'Airbyte'), ('airflow', 'Airflow'), ('code-server', 'Code-Server'), ('dbt-docs', 'Dbt-Docs'), ('grafana', 'Grafana'), ('local-dbt-docs', 'Local-Dbt-Docs'), ('superset', 'Superset')], max_length=50),
        ),
    ]
