# Generated by Django 3.2.20 on 2024-04-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_alter_environment_dbt_profiles_dir'),
        ('projects', '0097_auto_20240408_1710'),
    ]

    operations = [
    ]
