# Generated by Django 3.2.20 on 2024-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_merge_20240409_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='code_server_local_airflow_active',
            field=models.BooleanField(default=False),
        ),
    ]
