# Generated by Django 3.2.20 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0098_merge_20240409_1649"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="release_branch_protected",
            field=models.BooleanField(default=True),
        ),
    ]
