# Generated by Django 3.2.20 on 2024-05-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_project_release_branch_protected'),
        ('projects', '0099_userenvironment_code_server_local_airflow_active'),
    ]

    operations = [
    ]
