# Generated by Django 3.2.20 on 2024-06-03 16:44

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_merge_20240513_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvironment',
            name='local_airflow_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
