# Generated by Django 3.2.20 on 2024-06-12 02:11

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_userenvironment_local_airflow_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='datahub_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='elastic_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='kafka_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='neo4j_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='postgresql_config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='datahub_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='datahub_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='release',
            name='elastic_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='elastic_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='release',
            name='kafka_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='kafka_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='release',
            name='neo4j_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='neo4j_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='release',
            name='postgresql_chart',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='postgresql_images',
            field=models.JSONField(default=list),
        ),
    ]
