# Generated by Django 3.2.20 on 2024-06-14 13:33

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0101_userenvironment_local_airflow_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="userenvironment",
            name="code_server_config",
            field=core.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                editable=True,
                help_text="Extra configuration for user's code-server",
                null=True,
            ),
        ),
    ]
