# Generated by Django 3.2.20 on 2024-06-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_userenvironment_code_server_config'),
        ('projects', '0103_auto_20240612_0228'),
    ]

    operations = [
    ]
