# Generated by Django 5.0.7 on 2024-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0105_auto_20240701_2118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectiontemplate",
            name="connection_user",
            field=models.CharField(
                choices=[
                    ("provided", "User provided"),
                    ("email_username", "Inferred from email's username"),
                    ("template", "Inferred from user info using a custom template"),
                    ("email", "Inferred from email address"),
                    ("email_uppercase", "Inferred from uppercase email address"),
                ],
                default="provided",
                help_text="Can users configure their own credentials or are they restricted?  See the Model class documentation for full details.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profileimageset",
            name="airflow_requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of python libs to be used in airflow images, e.g. ["Django==5.0.7"]',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profileimageset",
            name="ci_requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of python libs to be used in ci images, e.g. ["Django==5.0.7"]',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profileimageset",
            name="code_server_requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of python libs to be used in code server images, e.g. ["Django==5.0.7"]',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profileimageset",
            name="python_requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of python libs to be used in both airflow and code server images, e.g. ["Django==5.0.7"]',
                null=True,
            ),
        ),
    ]
