# Generated by Django 5.0.7 on 2024-09-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0106_alter_connectiontemplate_connection_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileimageset",
            name="images_logs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Kubernetes logs", null=True
            ),
        ),
    ]
