# Generated by Django 5.0.7 on 2024-09-02 12:56

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0106_alter_connectiontemplate_connection_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="secrets_backend",
            field=models.CharField(
                choices=[
                    ("datacoves", "Datacoves"),
                    ("aws_secrets_manager", "AWS Secrets Manager"),
                ],
                default="datacoves",
                help_text="Secrets backend used to store/read secrets managed via admin.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="secrets_backend_config",
            field=core.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                editable=True,
                help_text="Configuration needed to connect to chosen secrets backend",
                null=True,
            ),
        ),
    ]
