# Generated by Django 5.0.7 on 2024-09-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0107_profileimageset_images_logs"),
        ("projects", "0107_project_secrets_backend_and_more"),
    ]

    operations = []
