# Generated by Django 5.0.7 on 2024-09-19 22:32

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_merge_20240905_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='azure_deploy_key',
            field=models.ForeignKey(blank=True, help_text='Required for Azure certificate clone strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.sslkey'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ci_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'Gitlab'), ('bamboo', 'Bamboo'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('other', 'Other'), ('azure_devops', 'Azure DevOps')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='clone_strategy',
            field=models.CharField(choices=[('ssh_clone', 'SSH git clone'), ('http_clone', 'HTTP git clone'), ('azure_secret_clone', 'Azure Secret clone'), ('azure_certificate_clone', 'Azure Certificate clone')], default='ssh_clone', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='deploy_credentials',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, help_text="Required for HTTP clone stategy.  This will be a JSON dictionary with keys 'git_username' and 'git_password'.  This is also used by the Azure deployments to provide azure_tenant and oauth credentials", null=True),
        ),
    ]
