# Generated by Django 5.0.7 on 2024-09-22 17:39

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_auto_20240922_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="For dynamic authentication, we need to have a unique ID to reference this project that isn't sequential as a security token.  Since this is internal only, we can restrict access to inside the Kubernetes cluster only, anad this is not accessible to end users so it should be sufficiently secure.", unique=True),
        ),
    ]
