# Generated by Django 5.0.7 on 2024-09-29 18:30

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_auto_20240922_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secrets_secondary_backend',
            field=models.CharField(blank=True, help_text="This is an Airflow class 'dot path' to enable the use of a secondary secret backend if the Datacoves Secret Backend is in use.", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='secrets_secondary_backend_config',
            field=core.fields.EncryptedJSONField(blank=True, editable=True, help_text='When a secondary backend is chosen, this is the Airflow configuration block for the backend.  It should be a bunch of key=value pairs.', null=True),
        ),
    ]
