# Generated by Django 5.0.7 on 2024-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0113_project_secrets_secondary_backend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentintegration",
            name="service",
            field=models.CharField(
                choices=[
                    ("airbyte", "Airbyte"),
                    ("airflow", "Airflow"),
                    ("code-server", "Code-Server"),
                    ("datahub", "Datahub"),
                    ("dbt-docs", "Dbt-Docs"),
                    ("grafana", "Grafana"),
                    ("local-dbt-docs", "Local-Dbt-Docs"),
                    ("superset", "Superset"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicecredential",
            name="service",
            field=models.CharField(
                choices=[
                    ("airbyte", "Airbyte"),
                    ("airflow", "Airflow"),
                    ("code-server", "Code-Server"),
                    ("datahub", "Datahub"),
                    ("dbt-docs", "Dbt-Docs"),
                    ("grafana", "Grafana"),
                    ("local-dbt-docs", "Local-Dbt-Docs"),
                    ("superset", "Superset"),
                ],
                max_length=50,
            ),
        ),
    ]
