# Generated by Django 5.0.7 on 2024-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_alter_environmentintegration_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecredential',
            name='delivery_mode',
            field=models.CharField(choices=[('env', 'Environment Variable'), ('connection', 'Airflow Connection')], default='env', max_length=16),
        ),
    ]
