# Generated by Django 5.0.7 on 2025-01-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0115_servicecredential_delivery_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentintegration",
            name="service",
            field=models.CharField(
                choices=[
                    ("airbyte", "Airbyte"),
                    ("airflow", "Airflow"),
                    ("code-server", "Code-Server"),
                    ("datahub", "Datahub"),
                    ("dbt-docs", "Dbt-Docs"),
                    ("local-dbt-docs", "Local-Dbt-Docs"),
                    ("superset", "Superset"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicecredential",
            name="service",
            field=models.CharField(
                choices=[
                    ("airbyte", "Airbyte"),
                    ("airflow", "Airflow"),
                    ("code-server", "Code-Server"),
                    ("datahub", "Datahub"),
                    ("dbt-docs", "Dbt-Docs"),
                    ("local-dbt-docs", "Local-Dbt-Docs"),
                    ("superset", "Superset"),
                ],
                max_length=50,
            ),
        ),
    ]
