# Generated by Django 5.0.7 on 2025-03-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0116_alter_environmentintegration_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilefile",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("0o644", "644"),
                    ("0o755", "755"),
                    ("0o600", "600"),
                    ("0o700", "700"),
                ],
                default="0o644",
                help_text="File permissions",
                max_length=5,
            ),
        ),
    ]
