# Generated by Django 5.0.7 on 2025-02-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0116_alter_environmentintegration_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="airflow_providers",
            field=models.JSONField(
                default=dict, help_text="Airflow library providers dictionary."
            ),
        ),
    ]
