# Generated by Django 5.0.7 on 2025-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0116_alter_environmentintegration_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userenvironment",
            name="code_server_active",
            field=models.BooleanField(default=False),
        ),
    ]
