# Generated by Django 5.0.7 on 2025-03-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_profilefile_permissions'),
        ('projects', '0117_release_airflow_providers'),
    ]

    operations = [
    ]
