# Generated by Django 5.0.7 on 2025-04-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_alter_userenvironment_code_server_active'),
        ('projects', '0118_merge_20250304_2206'),
    ]

    operations = [
    ]
