# Generated by Django 5.0.7 on 2025-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0119_merge_20250410_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefile',
            name='permissions',
            field=models.CharField(choices=[('0o644', '644'), ('0o744', '744'), ('0o600', '600'), ('0o700', '700')], default='0o644', help_text='File permissions', max_length=5),
        ),
    ]
