# Generated by Django 3.2.6 on 2022-03-03 15:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('provider', models.CharField(choices=[('eks', 'EKS (Amazon)'), ('gke', 'GKE (Google)'), ('aks', 'AKS (Azure)'), ('kind', 'Kind (local)')], default='kind', max_length=20)),
                ('cert_manager_issuer', models.CharField(blank=True, max_length=253, null=True)),
                ('external_dns_url', models.URLField(blank=True, null=True)),
                ('extra_images', models.JSONField(blank=True, default=list, null=True)),
                ('airbyte_logs_external', models.BooleanField(default=False)),
                ('airbyte_logs_provisioner', core.fields.EncryptedJSONField(default=dict)),
                ('airbyte_db_external', models.BooleanField(default=False)),
                ('airbyte_db_provisioner', core.fields.EncryptedJSONField(default=dict)),
                ('airflow_logs_external', models.BooleanField(default=False)),
                ('airflow_logs_provisioner', core.fields.EncryptedJSONField(default=dict)),
                ('airflow_db_external', models.BooleanField(default=False)),
                ('airflow_db_provisioner', core.fields.EncryptedJSONField(default=dict)),
                ('superset_db_external', models.BooleanField(default=False)),
                ('superset_db_provisioner', core.fields.EncryptedJSONField(default=dict)),
                ('fluentd_store_external', models.BooleanField(default=False)),
                ('fluentd_store_provisioner', core.fields.EncryptedJSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
