# Generated by Django 3.2.6 on 2022-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='kubernetes_version',
            field=models.CharField(default='1.20.7', max_length=40),
            preserve_default=False,
        ),
    ]
