# Generated by Django 3.2.6 on 2022-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_cluster_features_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='internal_dns_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='internal_dns_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
