# Generated by Django 3.2.6 on 2022-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_auto_20220517_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='external_dns_url',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='internal_dns_url',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
    ]
