# Generated by Django 3.2.6 on 2022-05-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_auto_20220517_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='release_channel',
            field=models.CharField(default='edge', max_length=20),
        ),
    ]
