# Generated by Django 3.2.6 on 2022-05-31 17:06

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_cluster_release_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='airbyte_db_provisioner',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airbyte_logs_provisioner',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airflow_db_provisioner',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airflow_logs_provisioner',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='fluentd_store_provisioner',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='superset_db_provisioner',
        ),
        migrations.AddField(
            model_name='cluster',
            name='blob_storage_provisioner',
            field=core.fields.EncryptedJSONField(default=dict, editable=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='postgres_db_provisioner',
            field=core.fields.EncryptedJSONField(default=dict, editable=True),
        ),
    ]
