# Generated by Django 3.2.6 on 2022-05-31 19:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0007_auto_20220531_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='blob_storage_provisioner',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='postgres_db_provisioner',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
