# Generated by Django 3.2.6 on 2022-06-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0008_auto_20220531_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='internal_db_cluster_ip_range',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
