# Generated by Django 3.2.6 on 2022-06-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_cluster_internal_db_cluster_ip_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='blob_storage_provisioner',
            new_name='s3_provisioner',
        ),
    ]
