# Generated by Django 3.2.6 on 2022-06-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0010_rename_blob_storage_provisioner_cluster_s3_provisioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='fluentd_store_external',
        ),
    ]
