# Generated by Django 3.2.6 on 2022-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0011_remove_cluster_fluentd_store_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='dont_use_uwsgi',
            field=models.BooleanField(default=False),
        ),
    ]
