# Generated by Django 3.2.6 on 2022-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0012_cluster_dont_use_uwsgi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='external_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='internal_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
