# Generated by Django 3.2.6 on 2022-09-20 20:02

import clusters.models.cluster
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_connection_connection_user'),
        ('clusters', '0013_auto_20220728_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='release',
            field=models.ForeignKey(default=clusters.models.cluster.default_release, on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='projects.release'),
        ),
    ]
