# Generated by Django 3.2.6 on 2022-09-20 22:17

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0014_cluster_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='airbyte_logs_external_backend',
            field=models.CharField(choices=[('s3', 'S3')], default='s3', help_text='Default logs backend when airbyte_logs_external is True', max_length=20),
        ),
        migrations.AddField(
            model_name='cluster',
            name='airflow_logs_external_backend',
            field=models.CharField(choices=[('s3', 'S3'), ('efs', 'EFS')], default='s3', help_text='Default logs backend when airflow_logs_external is True', max_length=20),
        ),
        migrations.AddField(
            model_name='cluster',
            name='efs_provisioner',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
