# Generated by Django 3.2.6 on 2022-10-19 20:25

import clusters.models.cluster
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0015_auto_20220920_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='limits',
            field=models.JSONField(blank=True, default=clusters.models.cluster.default_limits, null=True),
        ),
    ]
