# Generated by Django 3.2.6 on 2022-12-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_blockedpodcreationrequest'),
        ('clusters', '0016_cluster_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('namespace', models.CharField(blank=True, max_length=63, null=True)),
                ('summary', models.TextField()),
                ('data', models.JSONField()),
                ('environment', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.environment')),
            ],
        ),
    ]
