# Generated by Django 3.2.6 on 2022-12-23 13:23

import clusters.models.cluster
import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0016_cluster_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='docker_config',
            field=core.fields.EncryptedJSONField(blank=True, default=clusters.models.cluster.default_docker_config, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='docker_config_secret_name',
            field=models.CharField(blank=True, default='docker-config-datacovesprivate', max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='docker_registry',
            field=models.CharField(blank=True, max_length=253),
        ),
    ]
