# Generated by Django 3.2.16 on 2022-12-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0017_auto_20221223_1323'),
        ('clusters', '0017_clusteralert'),
    ]

    operations = [
    ]
