# Generated by Django 3.2.16 on 2023-01-20 18:21

import django.db.models.deletion
from django.db import migrations, models


def associate_cluster_alerts(apps, schema_editor):
    Cluster = apps.get_model("clusters", "Cluster")
    ClusterAlert = apps.get_model("clusters", "ClusterAlert")
    if ClusterAlert.objects.count() > 0:
        cluster = Cluster.objects.current().first()
        ClusterAlert.objects.update(cluster_id=cluster.id)


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0018_merge_0017_auto_20221223_1323_0017_clusteralert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clusteralert",
            name="summary",
        ),
        migrations.AddField(
            model_name="clusteralert",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clusters.cluster",
            ),
        ),
        migrations.RunPython(associate_cluster_alerts),
    ]
