# Generated by Django 3.2.16 on 2023-02-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0019_auto_20230120_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteralert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
