# Generated by Django 3.2.16 on 2023-02-10 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0020_clusteralert_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteralert',
            name='status',
            field=models.CharField(blank=True, choices=[('firing', 'Firing'), ('resolved', 'Resolved')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ClusterAlertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
        ),
        migrations.AddField(
            model_name='clusteralert',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clusters.clusteralertgroup'),
        ),
    ]
