# Generated by Django 3.2.16 on 2023-02-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_profile_files_from'),
        ('clusters', '0021_auto_20230210_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteralertgroup',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.environment'),
        ),
        migrations.AddField(
            model_name='clusteralertgroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clusteralertgroup',
            name='namespace',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
