# Generated by Django 3.2.16 on 2023-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0022_auto_20230211_0057"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clusteralert",
            name="group",
        ),
        migrations.AddField(
            model_name="clusteralert",
            name="started_at",
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name="ClusterAlertGroup",
        ),
    ]
