# Generated by Django 3.2.16 on 2023-03-06 20:13

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0023_auto_20230227_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='grafana_settings',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
