# Generated by Django 3.2.16 on 2023-03-14 12:11

import clusters.models.cluster
import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0024_cluster_grafana_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="alert_system_settings",
            field=models.JSONField(
                blank=True,
                default=clusters.models.cluster.default_alert_system_settings,
                help_text='Alert system settings, such as muted notifs ({"muted_notifications": [{"namespace": "cloudwatch", "name": "ContainerCpuUsage", "channel": "slack"}]}).',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="grafana_settings",
            field=core.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                editable=True,
                help_text="Grafana settings, such as OIDC secrets",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clusteralert",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clusters.cluster"
            ),
        ),
    ]
