# Generated by Django 3.2.16 on 2023-06-14 19:25

import clusters.models.cluster
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0025_auto_20230314_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='alert_system_settings',
            field=models.JSONField(blank=True, default=clusters.models.cluster.default_alert_system_settings, help_text='Alert system settings, such as muted notifs ({"muted_notifications": [{"namespace": "cloudwatch", "pod": "~worker-.*", "name": "=ContainerCpuUsage", "channel": "slack"}]}).', null=True),
        ),
    ]
