# Generated by Django 3.2.16 on 2023-09-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0026_alter_cluster_alert_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='api_server_ips',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
