# Generated by Django 3.2.16 on 2023-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0027_cluster_api_server_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='airbyte_db_external',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airbyte_logs_external',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airbyte_logs_external_backend',
        ),
        migrations.AddField(
            model_name='cluster',
            name='airbyte_config',
            field=models.JSONField(default=dict),
        ),
    ]
