# Generated by Django 3.2.20 on 2023-11-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0028_auto_20231023_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='code_server_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='airbyte_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
