# Generated by Django 3.2.20 on 2023-12-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0029_auto_20231101_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='airflow_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='superset_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
