# Generated by Django 3.2.20 on 2023-12-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0030_auto_20231207_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='clusters.cluster')),
            ],
        ),
    ]
