# Generated by Django 3.2.20 on 2024-01-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0031_clusterupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='celery_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
