# Generated by Django 3.2.20 on 2024-02-23 15:55

import clusters.models.cluster
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0032_cluster_celery_heartbeat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='settings',
            field=models.JSONField(blank=True, default=clusters.models.cluster.default_cluster_settings, null=True),
        ),
    ]
