# Generated by Django 3.2.20 on 2024-03-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0033_cluster_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='airflow_logs_external_backend',
            field=models.CharField(choices=[('s3', 'S3'), ('efs', 'EFS'), ('afs', 'AFS'), ('nfs', 'NFS')], default='s3', help_text='Default logs backend when airflow_logs_external is True', max_length=20),
        ),
    ]
