# Generated by Django 3.2.20 on 2024-04-02 01:01

import clusters.models.cluster
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0034_alter_cluster_airflow_logs_external_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='settings',
            field=models.JSONField(blank=True, default=clusters.models.cluster.default_cluster_settings, help_text="Configures 'admin_panel_color' (CSS color code) and 'code_server_inactivity_threshold' (minutes)", null=True),
        ),
    ]
