# Generated by Django 3.2.20 on 2024-06-05 22:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0035_alter_cluster_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='service_account',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, null=True),
        ),
    ]
