# Generated by Django 3.2.20 on 2024-06-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0035_alter_cluster_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='datahub_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
