# Generated by Django 3.2.20 on 2024-06-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0036_cluster_service_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='airflow_db_external',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airflow_logs_external',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='airflow_logs_external_backend',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='superset_db_external',
        ),
    ]
