# Generated by Django 3.2.20 on 2024-06-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0036_cluster_datahub_config'),
        ('clusters', '0037_auto_20240610_1936'),
    ]

    operations = [
    ]
