# permissions for end users to view helmreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmrelease-viewer-role
rules:
- apiGroups:
  - datacoves.com
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datacoves.com
  resources:
  - helmreleases/status
  verbs:
  - get
