# permissions for end users to view workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-viewer-role
rules:
- apiGroups:
  - datacoves.com
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datacoves.com
  resources:
  - workspaces/status
  verbs:
  - get
