# Generated by Django 3.2.6 on 2022-03-03 16:08

from django.db import migrations, models
import invitations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted')),
                ('key', models.CharField(default=invitations.models.get_invitation_key, max_length=64, unique=True, verbose_name='key')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail address')),
                ('name', models.CharField(max_length=130)),
            ],
        ),
    ]
