# Generated by Django 3.2.6 on 2022-11-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='Account invited email uniqueness',
        ),
    ]
