# Generated by Django 3.2.20 on 2024-07-01 21:18

from django.db import migrations, models
import invitations.models.invitation


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_remove_invitation_account_invited_email_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default=invitations.models.invitation.get_invitation_key, help_text='The invitation key used to accept the invitation.', max_length=64, unique=True, verbose_name='key'),
        ),
    ]
