# Generated by Django 3.2.6 on 2022-10-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('msteams', 'MS Teams'), ('slack', 'Slack'), ('sentry', 'Sentry')], max_length=50),
        ),
    ]
