# Generated by Django 3.2.20 on 2024-07-01 21:18

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='settings',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, editable=True, help_text='This is a JSON dictionary with settings.  Right now, only INTEGRATION_TYPE_SMTP settings are validated.', null=True),
        ),
    ]
