# Generated by Django 5.0.7 on 2025-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_integration_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Default integrations are automatically added to new Environments.",
            ),
        ),
    ]
