{
 "title": "Datacoves Nodes",
 "tags": [ "Datacoves" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_info, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_memory_Buffers_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_info) by (instance, internal_ip, kubelet_version, os_image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Node [$node]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{instance=\"$node\"}\n-\n  node_memory_MemFree_bytes{instance=\"$node\"}\n-\n  node_memory_Buffers_bytes{instance=\"$node\"}\n-\n  node_memory_Cached_bytes{instance=\"$node\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "memory free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "memory total"
    }
   ]
  },
  {
   "title": "Memory Usage by Node [$node]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg(node_memory_MemAvailable_bytes{instance=\"$node\"}) /\n  avg(node_memory_MemTotal_bytes{instance=\"$node\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Memory Free by Node [$node]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg(node_memory_MemFree_bytes{instance=\"$node\"}) /\n  avg(node_memory_MemTotal_bytes{instance=\"$node\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Node Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(kube_node_labels)", "legendFormat": "total" },
    {
     "expr": "sum (kube_node_labels{label_k8s_datacoves_com_nodegroup_kind!=\"\", label_k8s_datacoves_com_workers=\"\"}) by(label_k8s_datacoves_com_nodegroup_kind)",
     "legendFormat": "{{label_k8s_datacoves_com_nodegroup_kind}}"
    },
    {
     "expr": "sum (kube_node_labels{label_k8s_datacoves_com_nodegroup_kind=\"\", label_k8s_datacoves_com_workers=\"enabled\"}) by(pod)",
     "legendFormat": "workers"
    },
    {
     "expr": "sum (kube_node_labels{label_k8s_datacoves_com_nodegroup_kind!=\"\", label_k8s_datacoves_com_workers=\"enabled\"}) by(label_k8s_datacoves_com_nodegroup_kind)",
     "legendFormat": "{{label_k8s_datacoves_com_nodegroup_kind}} / worker"
    },
    {
     "expr": "sum (kube_node_labels{label_k8s_datacoves_com_nodegroup_kind=\"\", label_k8s_datacoves_com_workers=\"\"}) by(pod)",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_k8s_datacoves_com_workers=\"enabled\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}