{
 "title": "Datacoves Overview",
 "tags": [
  "Datacoves",
  "Accounts",
  "Environments",
  "Helm Charts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_slug",
    "label": "Account",
    "query": {
     "query": "label_values(datacoves_account_info,slug)"
    }
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Accounts and Environments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accounts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(datacoves_account_info{slug=~\"$account_slug\"}) by (name, slug, is_active, is_subscribed, is_on_trial, remaining_trial_days, developer_licenses)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(datacoves_environment_info{account_slug=~\"$account_slug\"}) by (name, slug, release_name, update_strategy, account_name, account_slug, project_name, project_slug)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Helm Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Helm Chart",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(datacoves_helm_chart_info{ns=~\"$ns\"}) by (name, namespace, status, chart, revision, app_version, updated)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}