{
 "title": "Datacoves Pods",
 "tags": [ "Datacoves" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Healthy by Namespace [$namespace]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas Mismatch by Namespace [$namespace]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "expected"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod [$namespace/$pod]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}) by (container)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}} - limit"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod [$namespace/$pod]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}) by (container)",
     "legendFormat": "{{container}} limit"
    }
   ]
  }
 ]
}