{
 "title": "Profile Image Set",
 "tags": [
  "Datacoves",
  "Profile Image Set"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "profile_name",
    "label": "Profile",
    "query": {
     "query": "label_values(kube_pod_labels{label_app=\"kaniko\"},label_k8s_datacoves_com_kaniko_profile_name)"
    }
   },
   {
    "name": "build_id",
    "label": "Build ID",
    "query": {
     "query": "label_values(kube_pod_labels{label_k8s_datacoves_com_kaniko_profile_name=\"$profile_name\"},label_k8s_datacoves_com_kaniko_build_id)"
    }
   },
   {
    "name": "image",
    "label": "Image",
    "query": {
     "query": "label_values(kube_pod_labels{label_k8s_datacoves_com_kaniko_build_id=\"$build_id\"},label_k8s_datacoves_com_kaniko_image)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"core\", pod=~\"kaniko.*\"} == 1"
    },
    {
     "expr": "time() - kube_pod_created{namespace=\"core\", pod=~\"kaniko.*\"}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"core\", pod=~\"kaniko.*\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"core\", pod=~\"kaniko.*\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Logs of all Pods",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=\"core\", pod=~\"kaniko-.*\"}"
    }
   ]
  },
  {
   "title": "Details by Pod [Kaniko-$build_id]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"core\", pod=\"kaniko-$build_id\", container=\"kaniko\"}) by (pod)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"core\", pod=\"kaniko-$build_id\", container=\"kaniko\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"core\", pod=\"kaniko-$build_id\", container=\"kaniko\"}[5m])) by (pod)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"core\", pod=\"kaniko-$build_id\", container=\"kaniko\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Kaniko Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{namespace=\"core\", pod=\"kaniko-$build_id\", container=\"kaniko\"}"
    }
   ]
  },
  {
   "title": "Webhook Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{namespace=\"core\", pod=\"kaniko-$build_id\", container=\"sidecar-webhook\"}"
    }
   ]
  }
 ]
}