# Generated by Django 3.2.6 on 2022-07-07 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20220707_1724'),
        ('users', '0002_user_is_service_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codegen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('connection_details', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_hooks', to='projects.connectiontype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_sql_hooks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codegen.template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
