# Generated by Django 3.2.6 on 2022-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0002_sqlhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlhook',
            name='trigger',
            field=models.CharField(choices=[('user_credential_post_save', 'User credential post save')], default='user_credential_post_save', max_length=50),
            preserve_default=False,
        ),
    ]
