# Generated by Django 3.2.6 on 2022-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0003_sqlhook_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='context_type',
            field=models.CharField(choices=[('user_credential', 'User credential'), ('dbt_profiles', 'DBT profiles')], max_length=30),
        ),
    ]
