# Generated by Django 3.2.6 on 2022-07-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0003_sqlhook_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlhook',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
