# Generated by Django 3.2.6 on 2022-07-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0004_alter_template_context_type'),
        ('codegen', '0004_auto_20220720_1914'),
    ]

    operations = [
    ]
