# Generated by Django 3.2.6 on 2022-07-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0005_merge_20220721_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='context_type',
            field=models.CharField(choices=[('user_credential', 'User credential'), ('user_credentials', 'User credentials')], max_length=30),
        ),
    ]
