# Generated by Django 3.2.6 on 2022-07-22 15:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0006_alter_template_context_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlhook',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
