# Generated by Django 3.2.6 on 2022-07-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0007_auto_20220722_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='is_global',
        ),
    ]
