# Generated by Django 3.2.6 on 2022-07-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0008_remove_template_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlhook',
            name='trigger',
            field=models.CharField(choices=[('user_credential_post_save', 'User credential post save'), ('user_credential_pre_save', 'User credential pre save')], max_length=50),
        ),
    ]
