# Generated by Django 3.2.6 on 2022-08-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0009_alter_sqlhook_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='context_type',
            field=models.CharField(choices=[('none', 'No context'), ('user_credential', 'User credential'), ('user_credentials', 'User credentials')], max_length=30),
        ),
        migrations.AlterField(
            model_name='template',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('python', 'Python'), ('bash', 'Bash'), ('sql', 'SQL'), ('sql_snowflake', 'Snowflake SQL'), ('sql_redshift', 'Redshift SQL'), ('sql_bigquery', 'BigQuery SQL')], max_length=30),
        ),
    ]
