# Generated by Django 3.2.6 on 2022-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0011_alter_template_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('python', 'Python'), ('bash', 'Bash'), ('sql', 'SQL'), ('sql_snowflake', 'Snowflake SQL'), ('sql_redshift', 'Redshift SQL'), ('sql_bigquery', 'BigQuery SQL'), ('sqlfluff', 'Sqlfluff'), ('sqlfluffignore', 'Sqlfluff Ignore'), ('html', 'HTML')], max_length=30),
        ),
    ]
