# Generated by Django 3.2.6 on 2022-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0012_alter_template_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='context_type',
            field=models.CharField(choices=[('none', 'No context'), ('user_credential', 'User credential'), ('user_credentials', 'User credentials'), ('environment', 'Environment')], max_length=30),
        ),
    ]
