# Generated by Django 3.2.6 on 2022-09-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_connection_connection_user'),
        ('codegen', '0013_alter_template_context_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlhook',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.environment'),
        ),
        migrations.AddField(
            model_name='sqlhook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
