# Generated by Django 3.2.6 on 2022-09-28 15:55

import autoslug.fields
import codegen.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codegen', '0014_auto_20220920_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlhook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sql_hooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sqlhook',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=codegen.models.sqlhook_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=codegen.models.template_slug, unique=True),
        ),
    ]
