# Generated by Django 3.2.16 on 2023-02-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0015_auto_20220928_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='context_type',
            field=models.CharField(choices=[('none', 'No context'), ('user_credential', 'User credential'), ('user_credentials', 'User credentials'), ('environment', 'Environment'), ('user', 'User')], help_text='Fields per context: user (email, name, username, slug), user credenial (user, ssl_public_key), user credenials (environment, connections), environment (dbt_home_path, type, slug, settings)', max_length=30),
        ),
        migrations.AlterField(
            model_name='template',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('python', 'Python'), ('bash', 'Bash'), ('sql', 'SQL'), ('sql_snowflake', 'Snowflake SQL'), ('sql_redshift', 'Redshift SQL'), ('sql_bigquery', 'BigQuery SQL'), ('sqlfluff', 'Sqlfluff'), ('sqlfluffignore', 'Sqlfluff Ignore'), ('html', 'HTML'), ('ini', 'INI config')], max_length=30),
        ),
    ]
