# Generated by Django 3.2.16 on 2023-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0016_auto_20230206_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='format',
            field=models.CharField(choices=[('none', 'No format'), ('json', 'JSON'), ('yaml', 'YAML'), ('python', 'Python'), ('bash', 'Bash'), ('sql', 'SQL'), ('sql_snowflake', 'Snowflake SQL'), ('sql_redshift', 'Redshift SQL'), ('sql_bigquery', 'BigQuery SQL'), ('sqlfluff', 'Sqlfluff'), ('sqlfluffignore', 'Sqlfluff Ignore'), ('html', 'HTML'), ('ini', 'INI config')], max_length=30),
        ),
    ]
