# Generated by Django 3.2.16 on 2023-02-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_update_account_permissions'),
        ('codegen', '0017_alter_template_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlhook',
            name='connection_template',
            field=models.ForeignKey(blank=True, help_text='If specified, this hooks will run on selected connection template only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.connectiontemplate'),
        ),
        migrations.AlterField(
            model_name='sqlhook',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='If specified, this hooks will run on selected environment only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='sqlhook',
            name='project',
            field=models.ForeignKey(blank=True, help_text='If specified, this hooks will run on selected project only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='sqlhook',
            name='template',
            field=models.ForeignKey(help_text='Template used to render the sql that will be ran.', on_delete=django.db.models.deletion.CASCADE, to='codegen.template'),
        ),
        migrations.AlterField(
            model_name='sqlhook',
            name='trigger',
            field=models.CharField(choices=[('user_credential_post_save', 'User credential post save'), ('user_credential_pre_save', 'User credential pre save')], help_text='Specifies the event that triggers this hook.', max_length=50),
        ),
    ]
