# Generated by Django 3.2.16 on 2023-02-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0018_auto_20230228_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlhook',
            name='connection_template',
        ),
        migrations.AddField(
            model_name='sqlhook',
            name='connection_templates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
