# Generated by Django 3.2.20 on 2023-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codegen", "0020_auto_20231017_1950"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sqlhook",
            old_name="connection_details",
            new_name="connection_overrides",
        ),
        migrations.AlterField(
            model_name="sqlhook",
            name="connection_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default connection info is taken from trigger context, this dict overrides them.",
                null=True,
            ),
        ),
    ]
