# Generated by Django 3.2.20 on 2024-07-01 21:18

import autoslug.fields
import codegen.models.template
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_auto_20240701_2118'),
        ('codegen', '0021_rename_connection_details_sqlhook_connection_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='account',
            field=models.ForeignKey(blank=True, help_text="If null, this is a system template.  System templates cannot be modified by users.  This isn't enforced by this field, though; it is enforced by created_by being null.", null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='If this is null, then it is a system template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text="Automatically generated.  If this is a global template, it is the template name with spaces turned into hypens.  If this is an account template, the account's slug is appended.  See AutoSlugField documentation for details on how the slugs are generated.", populate_from=codegen.models.template.template_slug, unique=True),
        ),
    ]
