# Generated by Django 5.0.7 on 2024-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codegen", "0022_auto_20240701_2118"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="enabled_for",
            field=models.JSONField(
                default=list,
                help_text="A JSON object that defines which classes can access this template.",
            ),
        ),
    ]
