# Generated by Django 5.0.7 on 2024-09-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0023_template_enabled_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='enabled_for',
            field=models.JSONField(default=list, help_text='List that defines which classes can access this template.'),
        ),
    ]
