# Generated by Django 5.0.7 on 2025-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0024_alter_template_enabled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlhook',
            name='public_key',
            field=models.TextField(null=True),
        ),
    ]
