name: Build and deploy pomerium-redis

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - prev
    paths:
      - src/pomerium/redis/*
      - src/pomerium/redis/**/*

jobs:
  build_and_deploy_pomerium-redis:
    name: Build and deploy pomerium-redis
    runs-on: ubuntu-latest

    container: datacoves/ci-multiarch:latest

    env:
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Trust directory
        run: git config --global --add safe.directory /__w/datacoves/datacoves

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build and deploy pomerium-redis
        run: ./cli.py ci_build_and_push pomerium/redis
        shell: bash
