name: Generate new GitHub release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  generate_release:
    name: Generate release
    runs-on: ubuntu-latest

    container: datacoves/ci-multiarch:latest

    env:
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DATACOVES_GITHUB_API_TOKEN: ${{ secrets.DATACOVES_GITHUB_API_TOKEN }}

    steps:
      - name: Trust directory
        run: git config --global --add safe.directory /__w/datacoves/datacoves

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate release
        run: ./cli.py generate_release
        shell: bash
