apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics-server-v0.6.2.yaml
  - ingress-nginx-v1.6.4.yaml

patchesStrategicMerge:
  - ingress-nginx-patch.yaml

secretGenerator:
  # TLS certificates for core namespace
  - name: default-tls
    namespace: ingress-nginx
    type: kubernetes.io/tls
    files:
      - tls.crt=wildcard.cer
      - tls.key=wildcard.secret.key
    options:
      disableNameSuffixHash: true
  - name: wildcard-tls
    namespace: core
    type: kubernetes.io/tls
    files:
      - tls.crt=wildcard.cer
      - tls.key=wildcard.secret.key
    options:
      disableNameSuffixHash: true
  - name: root-tls
    namespace: core
    type: kubernetes.io/tls
    files:
      - tls.crt=root.cer
      - tls.key=root.secret.key
    options:
      disableNameSuffixHash: true
